resources:
  limits:
    cpus: 2.0
    memory: 4096

change_detection:
  additional_envs: []

network:
  host_network: false
  http_port:
    bind_mode: published
    port_number: 5000

run_as:
  user: 568
  group: 568

storage:
  config:
    type: ix_volume
    mount_path: /datastore
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  additional_storage: []
