app_version: 1.0.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/dgtlmoon/changedetection.io/releases/
date_added: '2025-05-08'
description: "Page change monitoring with alerts a breeze. The best way to monitor website changes."
home: https://changedetection.io/
host_mounts: []
icon: https://user-images.githubusercontent.com/275001/231676626-7d768df9-be4c-4187-a573-aba640b826d3.svg
keywords:
- change-detection
- page monitoring
- price tracker
- stock tracker
lib_version: 2.1.16
lib_version_hash: dac15686f882b9ce65b8549a3d5c0ed7bafe2df7a9028880d1a99b0ff4af1eff
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: change-detection
run_as_context:
- description: changedetection.io runs as non-root user.
  gid: 101
  group_name: nginx
  uid: 101
  user_name: nginx
screenshots:
- https://raw.githubusercontent.com/dgtlmoon/changedetection.io/master/docs/screenshot.png
sources:
- https://github.com/dgtlmoon/changedetection.io
title: changedetection.io
train: community
version: 0.46.16
